--- 
pool: 
  vmImage: "Ubuntu 16.04"
steps: 
  - 
    script: |-
        dotnet build --configuration $(buildConfiguration)
        dotnet test DeepSpace.Core.Tests --configuration $(buildConfiguration)
variables: 
  buildConfiguration: Release
